### ISSUE TITLE
Dirty commit history

### ISSUE THREAD

**Issue by lthiery** [dewi-alliance/helium-jsonrpc-rs#7]
Is there a reason why `ae462e54b0f0530fe4a2c1cf84aa2bb58282b82e` isn't the first commit? Looks like `helium-api-rs` is in the commit history but this project truly started at the commit above.

**Comment by olb1ue** [comment]
This repo was originally a fork from helium-api-rs but @chrisabruce removed the fork status. We are probably ok to remove those old commits?
